### ISSUE TITLE
build on Debian squeeze fails

### ISSUE THREAD

**Issue by farzadghanei** [mozilla-services/heka-build#12]
Following the installation document, build fails on Debian squeeze.
###### make output

mkdir -p src/github.com/mozilla-services
cd src/github.com/mozilla-services && \
        git clone https://github.com/mozilla-services/heka.git && \
        cd heka && \
        git submodule update --init --recursive
Cloning into heka...
Submodule 'docs/source/_themes/mozilla' (https://github.com/ametaireau/mozilla-sphinx-theme.git) registered for path 'docs/source/_themes/mozilla'
Cloning into docs/source/_themes/mozilla...
Submodule path 'docs/source/_themes/mozilla': checked out '423fb2bd450273a90ed384eca08e4d1dd4dd9736'
mkdir -p release
cd release && cmake .. && make
-- The C compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Warning (dev) at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:167 (message):
  unknown ExternalProject_Add keyword: INSTALL_DIRECTORY
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1131 (_ep_parse_arguments)
  cmake/external_lua.cmake:12 (externalproject_add)
  CMakeLists.txt:62 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/farzad/heka-build/release
make[1]: Entering directory `/home/farzad/heka-build/release'
make[2]: Entering directory`/home/farzad/heka-build/release'
make[3]: Entering directory `/home/farzad/heka-build/release'
Scanning dependencies of target lua-5_1_5
make[3]: Leaving directory`/home/farzad/heka-build/release'
make[3]: Entering directory `/home/farzad/heka-build/release'
[  0%] Creating directories for 'lua-5_1_5'
[  0%] Performing download step (download, verify and extract) for 'lua-5_1_5'
-- downloading...
     src='http://www.lua.org/ftp/lua-5.1.5.tar.gz'
     dst='/home/farzad/heka-build/release/external/src/lua-5.1.5.tar.gz'
     timeout='none'
-- [download 100% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 14% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 19% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 31% complete]
-- [download 33% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 40% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 49% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 60% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 86% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 92% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 99% complete]
-- [download 100% complete]
-- downloading... done
-- verifying file...
     file='/home/farzad/heka-build/release/external/src/lua-5.1.5.tar.gz'
-- verifying file... done
-- extracting...
     src='/home/farzad/heka-build/release/external/src/lua-5.1.5.tar.gz'
     dst='/home/farzad/heka-build/release/external/src/lua-5_1_5'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  0%] Performing patch step for 'lua-5_1_5'
/bin/sh: cannot open /lua-5_1_5.patch: No such file
make[3]: *** [external/src/lua-5_1_5-stamp/lua-5_1_5-patch] Error 2
make[3]: Leaving directory`/home/farzad/heka-build/release'
make[2]: **\* [CMakeFiles/lua-5_1_5.dir/all] Error 2
make[2]: Leaving directory `/home/farzad/heka-build/release'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/home/farzad/heka-build/release'
make: **\* [sandbox] Error 2

**Comment by trink** [comment]
The patch step appears to be broken; it looks like ${CMAKE_CURRENT_LIST_DIR} is not being properly set but there is also a typo in the external_lua.cmake file.  Please change line 18 of external_lua.cmake to INSTALL_DIR instead of INSTALL_DIRECTORY and let me know if that fixes you problem.  If not please send me the version of cmake you are using.

cmake --version
cmake version 2.8.7

Thanks,
Trink

**Comment by farzadghanei** [comment]
Changed INSTALL_DIRECTORY to INSTALL_DIR yet failed in another place.
The problem is on external_lua.cmake line 16, as you mentioned ${CMAKE_CURRENT_LIST_DIR} is not set. I changed it to the exact path of heka-build/cmake/ and build was successful.

I'm using default cmake on Debian squeeze (updated). cmake version is 2.8.2

Thanks

**Comment by rafrombrc** [comment]
The hand generated Makefile will soon be superseded by a build process that is driven entirely by cmake, which obsoletes this issue.
