### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by ghost** [mozilla-services/heka-build#13]
mkdir -p release
cd release && cmake .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/aaronyue/github/heka-build/release
[100%] Built target lua-5_1_5
./scripts/setup_pluginloader.py
No external plugins loaded for the build.
GOPATH=OPATH PATH="/Users/aaronyue/github/heka-build/pythonVE/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:.:/pkg/tool/darwin_amd64:/Users/aaronyue/go/bin:/opt/local/bin:/opt/local/sbin:/platform-tools:/tools:/pkg/tool/darwin_amd64:/Applications/Utilities/instantclient_11_2" python scripts/update_deps.py package_deps.txt
destination directory: go-uuid
requesting all changes
adding changesets
adding manifests
adding file changes
added 10 changesets with 39 changes to 25 files
updating to branch default
14 files updated, 0 files merged, 0 files removed, 0 files unresolved

/bin/sh: /Users/aaronyue/github/heka-build/bin/go: is a directory
make: **\* [bin/hekad] Error 126

**Comment by crankycoder** [comment]
I'm not sure why heka-build/bin/go would be a directory.  Can you do a fresh clone of the repository and try again? 

Do you maybe have GOROOT  defined incorrectly?  Mine points to heka-build/build/go

**Comment by ghost** [comment]
IT WORKS!THANKS!
because I've set GOROOT=mygoroot before,SO  
before building 

```
export GOROOT= heka-build/build/go
```
