### ISSUE TITLE
Multiple 'make clean' options in cmake generated Makefiles

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka-build#25]
Right now running 'make clean' in a cmake generated branch directory will destructively delete any uncommitted or unpushed changes in any of the branch directory's repositories. Ideally 'make clean' itself would only delete the generated binaries, and a separate 'make clean-all' target would be added which performs the source code deletion.

**Comment by trink** [comment]
Build system is moving into Heka and you will no longer need to edit in the build directory.
