### ISSUE TITLE
Windows build complaining about missing lua_sandbox.go

### ISSUE THREAD

**Issue by Meai1** [mozilla-services/heka-build#26]
C:\libs\heka-build>cd release

C:\libs\heka-build\release>cmake .. -G"MinGW Makefiles"
CMake Error: File C:/libs/heka-build/src/github.com/mozilla-services/heka/sandbo
x/lua/lua_sandbox.go.in does not exist.
CMake Error at CMakeLists.txt:65 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!

C:\libs\heka-build\release>mingw32-make install
mingw32-make: **\* No rule to make target `install'.  Stop.

**Comment by rafrombrc** [comment]
Whoops, heka-build is deprecated. Heka's build process is now entirely driven by cmake, contained entirely within the main `heka` repository at https://github.com/mozilla-services/heka. I'll update the readme in this repo to reflect that.
