### ISSUE TITLE
Wrong folder names for go package "toml" and "hekad"

### ISSUE THREAD

**Issue by hellcoderz** [mozilla-services/heka-build#7]
make in heak-build repo gives two errors for go 1.0.3:

"bbangert" folder should be "BurntSushi"

<pre>github.com/mozilla-services/heka/pipeline/config.go:21:2: cannot find package "github.com/BurntSushi/toml</pre>

"hekad" folder should be inside "cmd/hekad"

<pre>can't load package: package github.com/mozilla-services/heka/cmd/hekad: cannot find package "github.com/mozilla-services/heka/cmd/hekad"</pre>

**Comment by rafrombrc** [comment]
This was a real bug, but not in heka-build, actually. Turns heka-build was expecting changes that a) were living on the heka project's dev branch, but hadn't yet been merged to heka master and b) hadn't even been completely done on dev. I've finished fixing up the import paths on dev, have merged them to master, and now a fresh checkout seems to be building cleanly again.

Thanks!
